/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.EvenementDAO;
import entities.Evenement;
import static java.lang.Integer.parseInt;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aymen
 */
public final class ListRubriqueFrame extends javax.swing.JFrame {

    EvenementDAO E = new EvenementDAO();
    Evenement e = new Evenement();

    /**
     * Creates new form Accueil
     */
    public ListRubriqueFrame() {
        initComponents();
        charger(E.DisplayAllEvenement());

    }

    public void charger(List<Evenement> L) {
        if (L.isEmpty()) {
            JOptionPane jop;
            jop = new JOptionPane();
            JOptionPane.showMessageDialog(null, "Rubrique Introuvable !", "Message Erreur", JOptionPane.ERROR_MESSAGE);
        }
        DefaultTableModel Tm = (DefaultTableModel) TableauList.getModel();

        for (Evenement e : L) {
            Tm.addRow(new Object[]{e.getIdEvenement(), e.getType(), e.getTitre(), e.getDescription(), e.getDateEvenement(), e.getDateHeure(), e.getDuree(), e.getIdAlum(), e.getIdImage(), e.getIdVideo(), e.getIdLieu(), e.getNbrVue()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RechercherPar = new javax.swing.JLabel();
        ListType = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableauList = new javax.swing.JTable();
        ListRecherche = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        PanneauRecherche = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        Labelle = new javax.swing.JLabel();
        TitreBox = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("JetSet");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 204));
        jLabel3.setText("Actu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahmed\\Documents\\icon\\home.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahmed\\Documents\\icon\\return.png")); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel18MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel18))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        RechercherPar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RechercherPar.setForeground(new java.awt.Color(255, 255, 255));
        RechercherPar.setText("Rechercher Par :");

        ListType.setBackground(new java.awt.Color(254, 254, 254));
        ListType.setFont(new java.awt.Font("Ubuntu Condensed", 0, 15)); // NOI18N
        ListType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----------", "News", "Art", "Films", "Soirees" }));
        ListType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListTypeMouseClicked(evt);
            }
        });
        ListType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListTypeActionPerformed(evt);
            }
        });
        ListType.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                ListTypeHierarchyChanged(evt);
            }
        });

        TableauList.setBackground(new java.awt.Color(254, 254, 254));
        TableauList.setForeground(new java.awt.Color(151, 151, 191));
        TableauList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idEvenemet","Type","Titre","Description","DateEvenemet","Heur","Duree","IDAlbume","IDImage","IDVideo","IDLieu","NbrVue"
            }
        ));
        TableauList.setSelectionForeground(new java.awt.Color(206, 57, 57));
        TableauList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableauListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableauList);

        ListRecherche.setFont(new java.awt.Font("Ubuntu Condensed", 0, 15)); // NOI18N
        ListRecherche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--------", "Date", "Titre", "ID" }));
        ListRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListRechercheMouseClicked(evt);
            }
        });
        ListRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListRechercheActionPerformed(evt);
            }
        });
        ListRecherche.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                ListRechercheHierarchyChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Types Rubriques :");

        PanneauRecherche.setBackground(new java.awt.Color(51, 51, 51));

        Labelle.setForeground(new java.awt.Color(254, 254, 254));
        Labelle.setText("Titre:");

        TitreBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitreBoxActionPerformed(evt);
            }
        });

        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanneauRechercheLayout = new javax.swing.GroupLayout(PanneauRecherche);
        PanneauRecherche.setLayout(PanneauRechercheLayout);
        PanneauRechercheLayout.setHorizontalGroup(
            PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanneauRechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Labelle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(PanneauRechercheLayout.createSequentialGroup()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanneauRechercheLayout.setVerticalGroup(
            PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauRechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanneauRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Labelle)
                    .addComponent(TitreBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ListType, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(RechercherPar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ListRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(PanneauRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ListType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ListRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RechercherPar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanneauRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        PanneauRecherche.setVisible(false);
        RechercherPar.setVisible(false);
        ListRecherche.setVisible(false);


    }//GEN-LAST:event_formWindowOpened

    private void ListTypeHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_ListTypeHierarchyChanged

    }//GEN-LAST:event_ListTypeHierarchyChanged

    private void ListTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListTypeActionPerformed
        // TODO add your handling code here:
        if (ListType.getSelectedIndex() != 0) {
            RechercherPar.setVisible(true);
            ListRecherche.setVisible(true);
            System.out.println(ListType.getSelectedIndex());

        } else {
            PanneauRecherche.setVisible(false);
            RechercherPar.setVisible(false);
            ListRecherche.setVisible(false);
        }
    }//GEN-LAST:event_ListTypeActionPerformed

    private void ListTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListTypeMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ListTypeMouseClicked

    private void ListRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListRechercheMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ListRechercheMouseClicked

    private String ReturnTypeOfRecherche(int i) {
        if (i == 1) {
            return "Date";

        } else if (i == 2) {
            return "Titre";

        } else if (i == 3) {
            return "ID";
        }
        return null;
    }

    private String ReturnTypeOfEvents(int i) {
        if (i == 1) {
            return "News";

        } else if (i == 2) {
            return "Art";

        } else if (i == 3) {
            return "Films";
        } else {
            return "Soirees";
        }

    }


    private void ListRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListRechercheActionPerformed
        if (ListRecherche.getSelectedIndex() != 0) {
            Labelle.setText(ReturnTypeOfRecherche(ListRecherche.getSelectedIndex()));
            PanneauRecherche.setVisible(true);
            System.out.println(ListType.getSelectedIndex());
        } else {
            PanneauRecherche.setVisible(false);
        }
    }//GEN-LAST:event_ListRechercheActionPerformed

    private void ListRechercheHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_ListRechercheHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ListRechercheHierarchyChanged

    private void TitreBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitreBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitreBoxActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        int i = ListType.getSelectedIndex();
//Recherche par Titre 
        if (Labelle.getText().equals("Titre")) {
            System.out.println("ok " + ReturnTypeOfEvents(i) + "//" + TitreBox.getText());
//clear the JTable  
            DefaultTableModel Tm = (DefaultTableModel) TableauList.getModel();
            Tm.getDataVector().removeAllElements();
//Fined and output the recherche  
            charger(E.DisplayAllEvenementbyTitreAndType(ReturnTypeOfEvents(i), TitreBox.getText()));

        }
//Recherche par ID
        if (Labelle.getText().equals("ID")) {
            try {
                int idEv = Integer.parseInt(TitreBox.getText());
                System.out.println("ok " + ReturnTypeOfEvents(i) + "//" + TitreBox.getText());
//clear the JTable  
                DefaultTableModel Tm = (DefaultTableModel) TableauList.getModel();
                Tm.getDataVector().removeAllElements();
//Fined and output the recherche
                charger(E.DisplayAllEvenementbyIDAndType(ReturnTypeOfEvents(i), idEv));
            } catch (Exception ex) {
                JOptionPane jop;
                jop = new JOptionPane();
                jop.showMessageDialog(null, "Erreur Dans L'insertion De Identifiant", "Message D'Erreur", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void TableauListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableauListMouseClicked
        int row = TableauList.getSelectedRow();

        String Table_Click = (TableauList.getModel().getValueAt(row, 0).toString());

        int id = parseInt(Table_Click);
//       //System.out.println(id);     
        e = E.findEvenementById(id);
        EvenementsBox EFram = new EvenementsBox();
        EFram.setVisible(true);
        EFram.EvenementAffiche(e);
    }//GEN-LAST:event_TableauListMouseClicked

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        AccueilGestionDesRubriqueAdmin a = new AccueilGestionDesRubriqueAdmin();
        a.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        Accueil a =new Accueil();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseReleased
        AccueilGestionDesRubriqueAdmin a =new AccueilGestionDesRubriqueAdmin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voircnvadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voircnvadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voircnvadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voircnvadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ListRubriqueFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labelle;
    private javax.swing.JComboBox ListRecherche;
    private javax.swing.JComboBox ListType;
    private javax.swing.JPanel PanneauRecherche;
    private javax.swing.JLabel RechercherPar;
    private javax.swing.JTable TableauList;
    private javax.swing.JTextField TitreBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    private RubriqueModel RubriqueModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
