/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DAO.ImageDAO;
import DAO.LieuDAO;
import entities.Image;
import entities.Lieu;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class ModifyLieuFram extends javax.swing.JFrame {

    /**
     * Creates new form AjouterLieuFram
     */
    public ModifyLieuFram() {
        initComponents();
        LienImageBox.setEnabled(false);
        LienImageBox.setText("Clique Ici");
        ID.setVisible(false);
//        LienMapBox.setEnabled(false);
//        LienMapBox.setText("Clique Ici");
        VisibleFalse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ModifiyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TelephoneBox = new javax.swing.JTextField();
        LienImageBox = new javax.swing.JTextField();
        LienMapBox = new javax.swing.JTextField();
        NomBox = new javax.swing.JTextField();
        EtInfo = new javax.swing.JLabel();
        EtNom = new javax.swing.JLabel();
        EtMap = new javax.swing.JLabel();
        EtImage = new javax.swing.JLabel();
        EtTel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InformatinBox = new javax.swing.JTextArea();
        ID = new javax.swing.JLabel();

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 204));
        jLabel15.setText("Actu");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("JetSet");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 3, 2));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 204));
        jLabel16.setText("Actu");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("JetSet");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(404, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(1, 1, 0));

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        ModifiyButton.setText("Modification");
        ModifiyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifiyButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Nom:");

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Information :");

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Adresse :");

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("LienImage :");

        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Telephone :");

        TelephoneBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelephoneBoxActionPerformed(evt);
            }
        });

        LienImageBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LienImageBoxMouseClicked(evt);
            }
        });
        LienImageBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LienImageBoxActionPerformed(evt);
            }
        });

        LienMapBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LienMapBoxMouseClicked(evt);
            }
        });
        LienMapBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LienMapBoxActionPerformed(evt);
            }
        });

        NomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomBoxActionPerformed(evt);
            }
        });

        EtInfo.setForeground(new java.awt.Color(254, 254, 254));
        EtInfo.setText("\"*\"");

        EtNom.setForeground(new java.awt.Color(254, 254, 254));
        EtNom.setText("\"*\"");

        EtMap.setForeground(new java.awt.Color(254, 254, 254));
        EtMap.setText("\"*\"");

        EtImage.setForeground(new java.awt.Color(254, 254, 254));
        EtImage.setText("\"*\"");

        EtTel.setForeground(new java.awt.Color(254, 254, 254));
        EtTel.setText("\"*\"");

        InformatinBox.setColumns(20);
        InformatinBox.setRows(5);
        jScrollPane1.setViewportView(InformatinBox);

        ID.setText("jLabel6");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ModifiyButton)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(126, 126, 126)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(NomBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                    .addComponent(EtNom))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(TelephoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EtTel))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(LienImageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EtImage))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(LienMapBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EtMap)))
                            .addComponent(EtInfo)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtNom))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LienMapBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtMap))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LienImageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtImage))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TelephoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtTel))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(ModifiyButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void  verifcation()
    {
        if(NomBox.getText().equals(""))
        {
            EtNom.setVisible(true);
        }
        if(InformatinBox.getText().equals(""))
        {
            EtInfo.setVisible(true);
        }
        if(LienMapBox.getText().equals(""))
        {
            EtMap.setVisible(true);
        }
        if(LienImageBox.getText().equals("Clique Ici"))
        {
            EtImage.setVisible(true);
        }if(TelephoneBox.getText().equals(""))
        {
            EtTel.setVisible(true);
        }
    }
   public void VisibleFalse()
   {
       EtImage.setVisible(false);
       EtInfo.setVisible(false);
       EtMap.setVisible(false);
       EtNom.setVisible(false);
       EtTel.setVisible(false);
   }
   public void Afficher(Lieu l)
   {
       ID.setText(l.getLieu()+"");
       NomBox.setText(l.getNom());
       LienMapBox.setText(l.getLienMap());
       LienImageBox.setText(l.getIdImage()+"");
       TelephoneBox.setText(l.getTel()+"");
       InformatinBox.setText(l.getInformation());
   }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AccueilGestionDesRubriqueAdmin a = new AccueilGestionDesRubriqueAdmin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LienImageBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LienImageBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LienImageBoxActionPerformed

    private void TelephoneBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelephoneBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelephoneBoxActionPerformed

    private void ModifiyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifiyButtonActionPerformed
        Lieu l = new Lieu();
        LieuDAO Lr = new LieuDAO();

        try {
           VisibleFalse();
            verifcation();
            l.setNom(NomBox.getText());
            l.setInformation(InformatinBox.getText());
            if(LienImageBox.getText().equals(""))
            {
            i1 = I.findImageByTitreAndLien(i.getTitre(), i.getLienImage());
            l.setIdImage(i1.getIdImage());
            }
            l.setLienMap(LienMapBox.getText());
            l.setTel(Integer.parseInt(TelephoneBox.getText()));

            System.out.println(l.toString());
            Lr.updateLieu(l,Integer.parseInt( ID.getText()));
            JOptionPane.showMessageDialog(null, "Modification effectuée Avec Succès", " Modifier", 1);
            ListLieuxFrameModifierAndSupprimer a = new ListLieuxFrameModifierAndSupprimer();
            a.setVisible(true);
            this.dispose();
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Erreur lors de la Modification", "Erreur Modifier", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_ModifiyButtonActionPerformed

    private void LienMapBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LienMapBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LienMapBoxActionPerformed

    private void NomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomBoxActionPerformed

    private void LienImageBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LienImageBoxMouseClicked
        String sh = JOptionPane.showInputDialog(null, "Veuillez saisire un Titre D'Image", "Nom Image", JOptionPane.QUESTION_MESSAGE);
        JFileChooser ch = new JFileChooser();
        ch.showOpenDialog(null);
        File f = ch.getSelectedFile();
        filename = f.getAbsolutePath();
        LienImageBox.setText(filename);
        i.setTitre(sh);
        i.setLienImage(filename);
        I.insertImage(i);
    }//GEN-LAST:event_LienImageBoxMouseClicked

    private void LienMapBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LienMapBoxMouseClicked
        //String sh = JOptionPane.showInputDialog(null, "Veuillez saisire un Titre D'Image", "Nom Image", JOptionPane.QUESTION_MESSAGE);
        
    }//GEN-LAST:event_LienMapBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyLieuFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyLieuFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyLieuFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyLieuFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyLieuFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtImage;
    private javax.swing.JLabel EtInfo;
    private javax.swing.JLabel EtMap;
    private javax.swing.JLabel EtNom;
    private javax.swing.JLabel EtTel;
    private javax.swing.JLabel ID;
    private javax.swing.JTextArea InformatinBox;
    private javax.swing.JTextField LienImageBox;
    private javax.swing.JTextField LienMapBox;
    private javax.swing.JButton ModifiyButton;
    private javax.swing.JTextField NomBox;
    private javax.swing.JTextField TelephoneBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
Image i =new Image();
Image i1 =new Image();
ImageDAO I = new ImageDAO();
String filename = null;

}
